// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNRtYwFdNDxYgumKwHjoMh6Q5sR94Htnc',
    appId: '1:415360089719:web:d229448974fc0f77f2d072',
    messagingSenderId: '415360089719',
    projectId: 'barzy-firestore-crud',
    authDomain: 'barzy-firestore-crud.firebaseapp.com',
    storageBucket: 'barzy-firestore-crud.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Z_qifJxIYZ5luT3472F4JrOdeZ1JHTE',
    appId: '1:415360089719:android:0365e7367ed404aff2d072',
    messagingSenderId: '415360089719',
    projectId: 'barzy-firestore-crud',
    storageBucket: 'barzy-firestore-crud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOVXCsBVvtyHXa2OuqPqlaf0biiwhQFMA',
    appId: '1:415360089719:ios:674ba23af581c811f2d072',
    messagingSenderId: '415360089719',
    projectId: 'barzy-firestore-crud',
    storageBucket: 'barzy-firestore-crud.appspot.com',
    iosClientId: '415360089719-vndak9etftbi8mnsae8ujtetsgts9er2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstInclassAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOVXCsBVvtyHXa2OuqPqlaf0biiwhQFMA',
    appId: '1:415360089719:ios:674ba23af581c811f2d072',
    messagingSenderId: '415360089719',
    projectId: 'barzy-firestore-crud',
    storageBucket: 'barzy-firestore-crud.appspot.com',
    iosClientId: '415360089719-vndak9etftbi8mnsae8ujtetsgts9er2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstInclassAssignment',
  );
}
